[build]
  publish = "dist"
  command = "yarn generate"

[build.environment]
  BASE_URL = "http://localhost:3000"

  AWS_FREETIER_URL = "http://ec2-13-125-77-236.ap-northeast-2.compute.amazonaws.com:3001"

  NAVER_MAPS_CLIENT_ID = "cd988t5b57"

  AA = "AA"
  BB = "BB"
  AA_BB = "AA_BB"
